# Generated by Django 5.2 on 2025-04-15 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-creado']},
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='fecha_actualizacion',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='contenido',
            new_name='cuerpo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='publicado',
        ),
        migrations.AddField(
            model_name='articulo',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10),
        ),
        migrations.AddField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(default='ejemplo-de-slug', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulos.categoria'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='articulos.etiqueta'),
        ),
    ]
