# Generated by Django 5.2 on 2025-04-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('lector', 'Lector'), ('columnista', 'Columnista'), ('editor', 'Editor')], default='lector', max_length=20),
        ),
    ]
