# Generated by Django 5.2 on 2025-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('lector', 'Lector'), ('autor', 'autor'), ('editor', 'Editor')], default='lector', max_length=20),
        ),
    ]
